INSERT INTO STUDENTS(FIRSTNAME, LASTNAME, STANDARD, ADDRESS, CONTACTNUMBER) VALUES('KISLAYA', 'ANAND', 'SEVENTH', 'BENGALURU - INDIA', 9876543210);
INSERT INTO STUDENTS(FIRSTNAME, LASTNAME, STANDARD, ADDRESS, CONTACTNUMBER) VALUES('JOHN', 'SMITH', 'SIXTH', 'UTAH - USA', 5567892342);
INSERT INTO STUDENTS(FIRSTNAME, LASTNAME, STANDARD, ADDRESS, CONTACTNUMBER) VALUES('VIKRAM', 'RAJ', 'SIXTH', 'BENGALURU - INDIA', 7892345678);
INSERT INTO STUDENTS(FIRSTNAME, LASTNAME, STANDARD, ADDRESS, CONTACTNUMBER) VALUES('ROHIT', 'KUMAR', 'FIFTH', 'DELHI - INDIA', 8561116729);
INSERT INTO STUDENTS(FIRSTNAME, LASTNAME, STANDARD, ADDRESS, CONTACTNUMBER) VALUES('ADITYA', 'PRATAP', 'TENTH', 'GUJRAT - INDIA', 9995671560);
